name: Build Docker container for Ubuntu
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
    paths:
      - "Ubuntu/**"
      - ".github/workflows/docker-buildpush-ubuntu.yaml"
  schedule:
    - cron: '23 8 */3 * *'

jobs:
  build-for-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get short tag
        run: echo "shorttag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: Ubuntu
          push: true
          tags: bynnchapu/docker-ansible-test:ubuntu,bynnchapu/docker-ansible-test:ubuntu-${{ env.shorttag }}
  test:
    runs-on: ubuntu-latest
    needs: build-for-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get short tag
        run: echo "shorttag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Install Goss
        uses: e1himself/goss-installation-action@v1.0.3
      - name: Start test image
        working-directory: ./test/Ubuntu/
        run: dgoss run -it bynnchapu/docker-ansible-test:ubuntu-${{ env.shorttag }}
  build-for-push:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref_name, 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get short tag
        run: echo "shorttag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: Ubuntu
          push: true
          tags: bynnchapu/docker-ansible:ubuntu,bynnchapu/docker-ansible:ubuntu-${{ env.shorttag }}