name: Build Docker container for AmazonLinux2
on:
  push:
    paths:
      - "AmazonLinux2/**"
      - ".github/workflows/docker-buildpush-amazonlinux2.yaml"
  schedule:
    - cron: '35 5 */3 * *'

jobs:
  build-for-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: AmazonLinux2
          push: true
          tags: bynnchapu/docker-ansible-test:amazonlinux2
  test:
    runs-on: ubuntu-latest
    needs: build-for-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Install Goss
        uses: e1himself/goss-installation-action@v1.0.3
      - name: Start test image
        working-directory: ./test/AmazonLinux2/
        run: dgoss run -it bynnchapu/docker-ansible-test:amazonlinux2
  build-for-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: AmazonLinux2
          push: true
          tags: bynnchapu/docker-ansible:amazonlinux2