name: Build Docker container for AmazonLinux2
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
    paths:
      - "AmazonLinux2/**"
      - ".github/workflows/docker-buildpush-amazonlinux2.yaml"
  schedule:
    - cron: '35 5 */3 * *'

jobs:
  build-for-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get short tag
        id: tag_info
        run: echo ::set-output name=SHORTTAG::$(git rev-parse --short HEAD)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: AmazonLinux2
          push: true
          tags: bynnchapu/docker-ansible-test:amazonlinux2,bynnchapu/docker-ansible-test:amazonlinux2-${{ steps.get_version.outputs.SHORTTAG }}
  test:
    runs-on: ubuntu-latest
    needs: build-for-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get short tag
        id: tag_info
        run: echo ::set-output name=SHORTTAG::$(git rev-parse --short HEAD)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Install Goss
        uses: e1himself/goss-installation-action@v1.0.3
      - name: Start test image
        working-directory: ./test/AmazonLinux2/
        run: dgoss run -it bynnchapu/docker-ansible-test:amazonlinux2-${{ steps.get_version.outputs.SHORTTAG }}
  build-for-push:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref_name, 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get short tag
        id: tag_info
        run: echo ::set-output name=SHORTTAG::$(git rev-parse --short HEAD)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: AmazonLinux2
          push: true
          tags: bynnchapu/docker-ansible:amazonlinux2,bynnchapu/docker-ansible:amazonlinux2-${{ steps.get_version.outputs.SHORTTAG }}